FROM mcr.microsoft.com/devcontainers/typescript-node:20

WORKDIR /repo

RUN corepack enable

COPY . .

RUN pnpm install --frozen-lockfile

ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

CMD ["pnpm", "--filter", "web", "dev", "--hostname", "0.0.0.0", "--port", "3000"]
