USE portfolio;

CREATE TABLE IF NOT EXISTS skills (
  id INT AUTO_INCREMENT PRIMARY KEY,
  locale VARCHAR(5) NOT NULL DEFAULT 'fr',
  name VARCHAR(160) NOT NULL,
  level VARCHAR(80) NULL,
  category VARCHAR(120) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS education (
  id INT AUTO_INCREMENT PRIMARY KEY,
  locale VARCHAR(5) NOT NULL DEFAULT 'fr',
  school VARCHAR(200) NOT NULL,
  degree VARCHAR(200) NULL,
  field VARCHAR(200) NULL,
  location VARCHAR(160) NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  description TEXT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
